"""initial_schema

Revision ID: 83b3706708e8
Revises: 
Create Date: 2026-10-03 01:08:16.380877

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '83b3706708e8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_identifier'), 'equipment', ['identifier'], unique=True)
    op.create_table('issue_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_report_id'), 'issue_report', ['id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("kind != 'confirmed' OR source = 'technician'", name='chk_finding_confirmed_technician'),
    sa.CheckConstraint("kind IN ('observation', 'possible_cause', 'confirmed')", name='chk_finding_kind'),
    sa.CheckConstraint("source IN ('ai', 'rules', 'technician')", name='chk_finding_source'),
    sa.ForeignKeyConstraint(['report_id'], ['issue_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_id'), 'finding', ['id'], unique=False)
    op.create_table('report_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('event_index', sa.Integer(), nullable=False),
    sa.Column('readings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['issue_report.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'event_index', name='uq_report_event_index')
    )
    op.create_index(op.f('ix_report_event_id'), 'report_event', ['id'], unique=False)
    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('proposed_steps', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(status = 'draft' AND reviewed_by IS NULL AND reviewed_at IS NULL) OR (status != 'draft' AND reviewed_by IS NOT NULL AND reviewed_by != '' AND reviewed_at IS NOT NULL)", name='chk_work_order_review'),
    sa.CheckConstraint("status IN ('draft', 'approved', 'rejected')", name='chk_work_order_status'),
    sa.ForeignKeyConstraint(['report_id'], ['issue_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_id'), 'work_order', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_id'), table_name='work_order')
    op.drop_table('work_order')
    op.drop_index(op.f('ix_report_event_id'), table_name='report_event')
    op.drop_table('report_event')
    op.drop_index(op.f('ix_finding_id'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_issue_report_id'), table_name='issue_report')
    op.drop_table('issue_report')
    op.drop_index(op.f('ix_equipment_identifier'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
